api:
  google:
    key: "{GOOGLE_API_KEY}"
    model: "gemini-2.0-flash-lite"
  openai:
    key: "{OPENAI_API_KEY}"
    url: "https://api.openai.com/v1/chat/completions"
    model: "gpt-4.0-mini"
  huggingface:
    key: "{HUGGINGFACE_API_KEY}"
    url: "https://router.huggingface.co/together/v1/chat/completions"
    model: "deepseek-ai/DeepSeek-V3"
  groq:
    key: "{GROQ_API_KEY}"
    url: "https://api.groq.com/openai/v1/chat/completions"
    model: "llama-3.1-8b-instant"
  openrouter:
    key: "{OPENROUTER_API_KEY}"
    url: "https://openrouter.ai/api/v1/chat/completions"
    model: "deepseek/deepseek-chat:free"
